version: "3"

services:
  react-native:
    #stdin_open: true
    #tty: true
    container_name: myreactnative-dev
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        USER: '${USER:-whoami}'
        USER_ID: '${USER_ID:-1000}'
        GROUP_ID: '${GROUP_ID:-1000}'
    volumes:
      - ./react-native-src:/app/react-native-src
    ports:
      - 19000:19000
      - 19001:19001
      - 19006:19006
      - 8081:8081
    #env_file:
    #  - ./.env
